name: zhongquanhuohuang
on:
  workflow_dispatch:
  schedule:
    - cron: '8 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongquanhuohuang
        env:
          gsxl42023: ${{ secrets.gsxl42023 }}
        run: |
          echo $gsxl42023 | jq -r .k462 | /bin/bash
          echo $jwhnw4594 | jq -r .ykkb31 | /bin/bash
          echo $kikf14655 | jq -r .rkwy516 | /bin/bash
          echo $nzb0 | jq -r .eis7961 | /bin/bash
          echo $c74 | jq -r .opr41 | /bin/bash
          echo $ekrh920 | jq -r .hmw2685 | /bin/bash
          echo $lv925 | jq -r .vrhlc492 | /bin/bash
          echo $ou247 | jq -r .csb3333 | /bin/bash

